##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
#
# Esempio di TCP Echo client e TCP Echo server 
# IPv4 only - no hostname resolution 
# uso dei wildcard IPv4 addresses
# 
##################################################

all: es1 es2

es1: es1.c
	gcc -ggdb -o es1 es1.c
	
es2: es2.c
	gcc -ggdb -o es2 es2.c

clean:
	rm es1 es2

##################################################