##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
#
# Esempio di TCP Echo client e TCP Echo server 
# IPv4 only - no hostname resolution 
# uso dei wildcard IPv4 addresses
# 
##################################################

all: S C

S: S.c
	gcc -ggdb -o S S.c

C: C.c
	gcc -ggdb -o C C.c

clean:
	rm S C 

##################################################