##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
#
# Esempio di TCP Echo client e TCP Echo server 
# IPv4 only - no hostname resolution 
# uso dei wildcard IPv4 addresses
# 
##################################################

all: SC1 SC2 SC3

SC1: SC1.c
	gcc -ggdb -o SC1 SC1.c

SC2: SC2.c
	gcc -ggdb -o SC2 SC2.c

SC3: SC3.c
	gcc -ggdb -o SC3 SC3.c
	
clean:
	rm SC1 SC2 SC3

##################################################