##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
#
# Esempio di TCP Echo client e TCP Echo server 
# IPv4 only - no hostname resolution 
# uso dei wildcard IPv4 addresses
# 
##################################################

all: P1 P2P3

P1: P1.c
	gcc -ggdb -o P1 P1.c
	
P2P3: P2P3.c
	gcc -ggdb -o P2P3 P2P3.c

clean:
	rm P1 P2P3

##################################################