##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
#
# Esempio di TCP Echo client e TCP Echo server 
# IPv4 only - no hostname resolution 
# uso dei wildcard IPv4 addresses
# 
##################################################

all: memCond

memCond: memCond.c
	gcc -ggdb -o memCond memCond.c

clean:
	rm memCond

##################################################