##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
#
# Esempio di TCP Echo client e TCP Echo server 
# IPv4 only - no hostname resolution 
# uso dei wildcard IPv4 addresses
# 
##################################################

all: time_counter
time_counter: time_counter.c
	gcc -ggdb -o time_counter time_counter.c

clean:
	rm time_counter

##################################################