##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
#
# Esempio di TCP Echo client e TCP Echo server 
# IPv4 only - no hostname resolution 
# uso dei wildcard IPv4 addresses
# 
##################################################

all: sharedMemUDP UDPClient

sharedMemUDP: search.c
	gcc -ggdb -o search search.c

clean:
	rm search 

##################################################