##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
#
# Esempio di TCP Echo client e TCP Echo server 
# IPv4 only - no hostname resolution 
# uso dei wildcard IPv4 addresses
# 
##################################################

all: pipe
pipe: pipe.c
	gcc -ggdb -o pipe pipe.c

clean:
	rm pipe 

##################################################