##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
#
# Esempio di TCP Echo client e TCP Echo server 
# IPv4 only - no hostname resolution 
# uso dei wildcard IPv4 addresses
# 
##################################################

all: p1 p2
p1: p1.c
	gcc -ggdb -o p1 p1.c

p2: p2.c
	gcc -ggdb -o p2 p2.c

clean:
	rm p1 p2

##################################################