##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
#
# Esempio di TCP Echo client e TCP Echo server 
# IPv4 only - no hostname resolution 
# uso dei wildcard IPv4 addresses
# 
##################################################

all: P1 P2

P1: P1.c
	gcc -ggdb -o P1 P1.c

P2: P2.c
	gcc -ggdb -o P2 P2.c

clean:
	rm P2 P1

##################################################