##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
#
# Esempio di TCP Echo client e TCP Echo server 
# IPv4 only - no hostname resolution 
# uso dei wildcard IPv4 addresses
# 
##################################################

all: esameSNP43  

TCPUDPServer: esameSNP43.c
	gcc -ggdb -o esameSNP43 esameSNP43.c

clean:
	rm esameSNP43  

##################################################