##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
#
# Esempio di TCP Echo client e TCP Echo server 
# IPv4 only - no hostname resolution 
# uso dei wildcard IPv4 addresses
# 
##################################################

all: signalHandler 

signalHandler: signalHandler.c
	gcc -ggdb -o signalHandler signalHandler.c

clean:
	rm signalHandler

##################################################