##################################################
# Makefile 
#
# author Catiuscia Melle
#
# Compilazione degli example codes 
#
# Esempio di TCP Echo client e TCP Echo server 
# IPv4 only - no hostname resolution 
# uso dei wildcard IPv4 addresses
# 
##################################################

all: semSystemV
semSystemV: semSystemV.c
	gcc -ggdb -o semSystemV semSystemV.c

clean:
	rm semSystemV 

##################################################